### ISSUE TITLE
Automatically send a message from matlab

### ISSUE THREAD

**Issue by kurtulik1** [jebej/MatlabWebSocket#11]
Hey, 
I am trying to change a client code, so every time my Matlab client gets some message, it does something with it and send automatically another message back. 
I am a bit lost in Java library. 
Any suggestions?

Thanks

**Comment by jebej** [comment]
You shouldn’t need to touch the java code. Look at the echo server example.

**Comment by kurtulik1** [comment]
I use only Client code of websocket. The server in node server.

**Comment by jebej** [comment]
The client code will be very similar to the server code, except instead of
having the server reply to the client, you’ll have the client reply to the
server. Either way you need to use the “send” function.

**Comment by kurtulik1** [comment]
Maybe I didnt write it clear enough.

My matlab is a client and it is connected to ws server. The server will send a request to Matlab, and matlab should automaticaly answer based on the request. For example The server send 2+3, and the matlab will calculate it and send the answer 5.

SOLVED!
