### ISSUE TITLE
How to use Matlabwebsocket in simulink. Need to support code generation as well. 

### ISSUE THREAD

**Issue by iamrajeswar59** [jebej/MatlabWebSocket#12]
Hi Jebeg, 

This is a very helpful package. I have used it in matlab and i was able to get data from browser without any issues. I have User interface in html and i am trying to connect to simulink. This is requirement from my customer. So we need to recieved data continuosly during simulation. 

We should also support code generation. Simulink coder or embedded coder. 

I tried a lot to get it working. Simulation is working fine. But having issues with code generation. The executable gets generated but after executing nothing happens. 

Can you please assist.

**Comment by jebej** [comment]
This question appears to be more of a general MATLAB issue, does not seem directly relevant to this project, so I'll close it.
