### ISSUE TITLE
Adding additional/custom headers

### ISSUE THREAD

**Issue by stfnp** [jebej/MatlabWebSocket#14]
The class `WebSocketClient` from the underlying Java-WebSocket has the constructor [WebSocketClient( URI serverUri, Map<String,String> httpHeaders)](https://github.com/TooTallNate/Java-WebSocket/blob/a89d4aeec5befaaa1ef8ebc20ed643509ebf03e5/src/main/java/org/java_websocket/client/WebSocketClient.java#L173) that takes additional http headers as an argument. Is it possible to do something similar with MatlabWebSocket? It seems like this isn't exposed in the API, but maybe I just didn't find it. A common use case would be authentication, i.e. sending a username and password hash when establishing a connection.

I would be willing to work on this if you consider such a feature useful and in scope for MatlabWebSocket.

**Comment by jebej** [comment]
Hey, yes I would certainly find this useful. As long as the argument is optional that would be fine.

**Comment by stfnp** [comment]
Okay, cool. I will have a deeper look then and start working on something.

**Comment by jebej** [comment]
Closed by #15
