### ISSUE TITLE
Get data from JSON Websocket Viewer

### ISSUE THREAD

**Issue by ngocthangbme** [jebej/MatlabWebSocket#16]
Dear Jebej, 

I am working with Leap Motion. In my research, I want to connect multiple leap motion, but the problem is I don't know how to get data from this one. Since I use Matlab Websocket to get data from JSON Websocket Viewer, but when I perform follow your instructions It just displays the received message. I can not put the data into the file (.txt or .xlsx something like that)
Below is the link I use to describe the problem
https://drive.google.com/drive/u/0/folders/1U6nJTQiCLMAf-BO2N2PKhPG5Poi4i_Yf
Please help me to solve it.
Thank you very much

**Comment by jebej** [comment]
You will have to program a client class which does what you want upon receiving the data. Read the usage section in the readme and let me know if you have a more concrete question after.
