### ISSUE TITLE
NullPointerException after running for 20 mins

### ISSUE THREAD

**Issue by jnblanchet** [jebej/MatlabWebSocket#2]
Hello,

My MATLAB server crashes after about 20 mins of execution:

`Exception in thread "WebsocketSelector123" java.lang.NullPointerException
    at org.java_websocket.matlabbridge.MatlabWebSocketServerBridge.onError(MatlabWebSocketServerBridge.java:107)
    at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:462)
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:392)
    at java.lang.Thread.run(Unknown Source)`

Tested on both Linux and Windows. Any idea what could cause this?

**Comment by jebej** [comment]
Hey, I have never encountered this problem, and I have run a server 24/7 for almost a year now.

Is that the only error message you see? Does that happen with the example echo server?

Also, what MATLAB version are you using? (please run `version` and `version -java`)

**Comment by jnblanchet** [comment]
Hey thanks for the reply!
MATLAB version 8.6.0.267246 (R2015b)
Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

I did some digging, and found the exact line that causes an issue (with a better stack trace):

> java.lang.NullPointerException
>     at org.java_websocket.SocketChannelIOHelper.batch(SocketChannelIOHelper.java:64)
>     at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:362)
>     at java.lang.Thread.run(Unknown Source)

which is the following if statement in SocketChannelIOHelper.java:

```
if( ws.outQueue.isEmpty() && ws.isFlushAndClose() && ws.getDraft().getRole() == Role.SERVER ) {
    synchronized ( ws ) {
        ws.closeConnection();
    }
}
```

There were no connection attempts, and the server crashed after about 6 hours.
Could it be some sort of race condition?
I tried adding a try/catch around those lines to see if it fixes something. I'll know tomorrow.
EDIT: I'm also running the echo server, so I'll check if the same error happens.

**Comment by jnblanchet** [comment]
So I haven't had a crash in 12 hours with the try/catch, and the server is still up and running. Not a very elegant solution, but a quick and dirty fix that does the job. Here's the jar I used for anyone else having this issue.
[matlabwebsocket_jar.zip](https://github.com/jebej/MatlabWebSocket/files/365161/matlabwebsocket_jar.zip)

**Comment by jebej** [comment]
Thanks!
