### ISSUE TITLE
free port fails if delete(server) is omitted

### ISSUE THREAD

**Issue by ghost** [jebej/MatlabWebSocket#5]
First of all, your websocket wrapper for matlab is awesome :)

I wonder if this is bug though: If i just do the seq:
```
clc
clear
clear all
```
the port is not freed and i cannot start the server on the same port again unless i add delete|stop(server):
```
delete(server) % free port
clc
clear
clear all

```
if i overwrite the destructor in EchoServer, the destructor gets called but probably after matlab's garbage collection, not freeing the port. How to solve this?

        %         function delete(obj)  % free port if clear is called
        %             stop(obj) %err obj is alread deleted?
        %         end

**Comment by jebej** [comment]
As mentioned in the readme, the proper way to delete the server is to manually call `delete` on the object. This will free the port. Simply clearing the variable will not work.

**Comment by ghost** [comment]
with the standalone application compiler i get reference error on these lines of websocketserver:
   l66/69            eg.  import io.github.jebej.matlabwebsocket.MatlabWebSocketSSLServer;

i cannot figure out how to import your repository on a standalone, the imports are not defined because there is no classpath, though i import the .jar file, termination log:
How to make the imports work, i do add the files required by the application to matlab in the wizard.
It seems to be path issue, what to do before import?
> 
> mcc -o test -W main:test -T link:exe -d /home/user/matlab/serverLogic/standalone/test/for_testing -v /home/user/matlab/serverLogic/main.m -a /home/user/3party/MatlabWebSocket/jar/matlab-websocket-1.3.jar 
> Compiler version: 6.4 (R2017a)
> 
> Dependency analysis by REQUIREMENTS.
> 
> Unexpected error while determining required deployable files. Compilation terminated. Details:
> Error using getSymbolNames
> Import argument "io.github.jebej.matlabwebsocket.MatlabWebSocketSSLServer" in MATLAB code '/home/user/matlab/serverLogic/main.m' cannot be found or cannot be imported.
> 

i tried to change the path but without success:
`import matlab-websocket-1.3.io.github.jebej.matlabwebsocket.MatlabWebSocketSSLServer
`

**Comment by jebej** [comment]
I actually haven't tried using the Application Compiler with external java classes and so I cannot help you.

I suggest you Google around, maybe starting with this link:
https://www.mathworks.com/matlabcentral/answers/97072-how-should-i-include-a-jar-file-in-my-compiled-application-with-matlab-compiler-4-1-r14sp1

If you do manage to get it to work, I would appreciate a pull request to the README with explanations on how you did it.

In the meantime, I will close the issue since you don't seem to be having problems with the port freeing anymore.

**Comment by ghost** [comment]
digging into the wrapped lib i'll move away from [Java-WebSocket repo](https://github.com/TooTallNate/Java-WebSocket), and found the "official" ws implementation in java on [http://mvnrepository.com/artifact/javax.websocket/javax.websocket-api](http://mvnrepository.com/artifact/javax.websocket/javax.websocket-api). I will use UDP to node.js and its ws <br>  <br> The code/doc is located in http://central.maven.org/maven2/javax/websocket/javax.websocket-api/ and `/javaws/javax.websocket-api-1.1-sources/javax/websocket/Endpoint.java` in the sources file has some nice examples on how to extend it, in case you consider wrapping it in matlab
