### ISSUE TITLE
Cannot Connect to WSS

### ISSUE THREAD

**Issue by ramsys28** [jebej/MatlabWebSocket#7]
Hi,

Thank you very much for this tool. I have installed and test it in ws, but when I am trying to access a wss I got this error: 
Error: sun.security.validator.ValidatorException: No trusted certificate found
Error: sun.security.validator.ValidatorException: No trusted certificate found
Disconnected from server at

Although I made a self-signed certificate as you mention and point the SimpleClient to the jks that I made. 

Considering that I don't know Java at all could you please help me to solve this? 

Thank you very much in advance
Manos

**Comment by jebej** [comment]
Both the server and client need to access the `jks` file. Check out the test file to see how both the client and server are constructed and tell me if you still have problems after that.
