### ISSUE TITLE
Cannot connect due to "Received fatal alert: protocol_version"

### ISSUE THREAD

**Issue by Benvaulter** [jebej/MatlabWebSocket#8]
I am trying to connect to the cex.io websocket (https://cex.io/cex-api) like so:
`cex = SimpleClient('wss://ws.cex.io/ws');`

However, I receive the following error:
`>> cex = SimpleClient('wss://ws.cex.io/ws');
Error: Received fatal alert: protocol_version
Error: Received fatal alert: protocol_version
Disconnected from server at wss://ws.cex.io/ws`

I have had similar issues with cex.io before when trying to fetch data using urlread2 for example. Switching to "webread" and "webwrite" solved the issue for me at least for the RESTful applications. Any idea on how to handle this issue?

Thanks in advance!

**Comment by jebej** [comment]
This works fine for me: 
```matlab
>> cex = SimpleClient('wss://ws.cex.io/ws');
Connected to server at wss://ws.cex.io/ws
Message received:
{"e":"connected"}
```
