### ISSUE TITLE
Arguments to IMPORT must either end with ".*" 

### ISSUE THREAD

**Issue by ecleipteon** [jebej/MatlabWebSocket#9]
Hey,

I got this error when tried running the client example on Matlab R2018a

> Arguments to IMPORT must either end with ".*" or else specify a fully qualified class name: "io.github.jebej.matlabwebsocket.MatlabWebSocketSSLClient" fails this test.

any guessing?

thank you 
best
luca

**Comment by ecleipteon** [comment]
My fault, I made a silly mistake in configuring the javapath.
Closing the issue :)

**Comment by tecnoloco** [comment]
What was the mistake? I added the configuration to javapath but I get the same error.

**Comment by tecnoloco** [comment]
Forget it I just saw my silly mistake too. I copied the file name in README but my actual file has a different version.

README = matlab-websocket-1.3.jar

Mine = matlab-websocket-1.4.jar
